### ISSUE TITLE
Issue!

### ISSUE THREAD

**Issue by Napoleon-ZoomberParts** [josephworks/flame#1]
Where are the autumn values?

**Comment by josephworks** [comment]
Great question, I'll assign @GardeningTool

**Comment by GardeningTool** [comment]
Hello. If you'd like Autumn values, I'd suggest Fan client.

Thanks!

**Comment by Napoleon-ZoomberParts** [comment]
> 
> 
> Hello. If you'd like Autumn values, I'd suggest Fan client.
> 
> Thanks!

Thanks for the suggestions, I heard those values get Cedo horny so I had to see what the fuss was about

**Comment by GardeningTool** [comment]
I can confirm that they do indeed.
